### ISSUE TITLE
Markdown files have almost no syntax highlighting

### ISSUE THREAD

**Issue by hisaac** [Monokai/monokai-pro#11]
![monokai-pro-markdown](https://user-images.githubusercontent.com/923876/27660408-ae79eca2-5c1c-11e7-960b-a3bd43386699.png)

When using Monokai Pro to edit Markdown files, there is almost no syntax highlighting at all. Is this something that can be added?

**Comment by pastorryanhayden** [comment]
+1 On this.
Just purchased the theme and I do A LOT of writing in Markdown.  Syntax highlighting here is a must.

**Comment by Monokai** [comment]
Just added Markdown syntax highlighting in 1.0.3.

**Comment by hisaac** [comment]
Looks great. Even [Markdown Extended](https://github.com/jonschlinkert/sublime-markdown-extended) works. Thank you!
