### ISSUE TITLE
support payments in crypto?

### ISSUE THREAD

**Issue by Jawabiscuit** [Monokai/monokai-pro#12]

**Comment by Monokai** [comment]
Unfortunately that's not supported at the moment, as my payment processor only uses Paypal. Maybe you're able to transfer cryptocoins to a Paypal account?

**Comment by Jawabiscuit** [comment]
worth it.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by Jawabiscuit** [comment]
Sorry ignore the previous. I just meant support crypto! ;) I will use Paypal with credit card.

Sent with [ProtonMail](https://protonmail.com) Secure Email.
