### ISSUE TITLE
theme not selectable under linux

### ISSUE THREAD

**Issue by jnials** [Monokai/monokai-pro#2]
I have installed this, the theme doesn't seem to work under linux (or at least I cannot choose it).  Seems to work fine under OSX, but I do most of my development under linux, so that's a non-starter for me.

**Comment by Monokai** [comment]
Hey @jnials can you please let me know the relevant output of your console? I did test it on Linux, but I probably overlooked something.

**Comment by kiddick** [comment]
Same here
``` python
Traceback (most recent call last):
  File "./dist/utils/select_theme.py", line 141, in on_done
  File "./dist/utils/select_theme.py", line 38, in create_template
  File "/opt/sublime_text/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
```

**Comment by Monokai** [comment]
Not sure how this is possible. Testing it on a fresh install of Ubuntu 16.10 seems to work fine. I've included an extra error message in the console view in version 1.0.2 that prints the filename that Sublime is trying to load. Do you see that in the console perhaps?

**Comment by kiddick** [comment]
@Monokai works for me now :)

**Comment by Monokai** [comment]
I'm glad but I don't really understand :) Didn't change anything in the file loading logic.

**Comment by Monokai** [comment]
@jnials does it work for you now?

**Comment by jnials** [comment]
Yup.  It's working.
