### ISSUE TITLE
No visual feedback when cycling through autocompletions

### ISSUE THREAD

**Issue by AlexKvazos** [Monokai/monokai-pro#4]
Description: Autocompletions can be cycled using *arrow keys*, the selected completion will have visual feedback such as a different background, different text color, etc.. However, this theme doesn't differentiate between the selected completion and the rest.

Expected behavior: See a visual feedback when cycling completions as following example:

![expected](https://user-images.githubusercontent.com/4448627/27108202-79649bb4-5061-11e7-8934-b5de554f2573.gif)

Actual behavior: No visual feedback is shown and we have to mentally keep track of what row we currently are at.
![screenflow](https://user-images.githubusercontent.com/4448627/27108215-8d4bc2ec-5061-11e7-88e0-f42f4739e9c3.gif)

Using Sublime Text 3136 on macOS 10.12.5

**Comment by Monokai** [comment]
Good catch. Fixed in 1.0.2.
