### ISSUE TITLE
No file icon for Scss files

### ISSUE THREAD

**Issue by julienvanderkluft** [Monokai/monokai-pro#6]
Files with a `.scss` extension do not have any file icon in sidebar.

**Comment by Monokai** [comment]
@julienvanderkluft do you have syntax highlighting for Sass installed? is your extension .scs? what icon is displayed instead?

**Comment by julienvanderkluft** [comment]
Syntax highlighting for Sass ✅
Extension `.scss` ✅

File icon image for `.scss` doesn't exist, i have simply no icon displayed.

But, if i duplicate the 3 `file_type_sass.png` to `file_type_scss.png` in theme folder, it works.

**Comment by Monokai** [comment]
Hmm, not sure. What I do know is that it's possible that you have conflicting file type definitions. When you have multiple themes installed, Sublime collects all file type definitions, even if you don't use the theme. It's possible the file type is defined elsewhere. I also renamed the icon and file type definition to .scss instead of .sass, but I'm not sure that's the main problem.

**Comment by julienvanderkluft** [comment]
I tried on a clean session, with only Sass syntax installed. So I do not know with what there may be a conflict.

Anyway, it works fine now with the update, for both `.scss`and `.sass`ext.

**Comment by ralts00** [comment]
I have the same problem, it does not recognize any icon for: .scss
![captura de pantalla 2017-11-02 17 08 47](https://user-images.githubusercontent.com/5034252/32354705-e1e4b5c8-bff8-11e7-8bbe-bf4f577be4c8.png)

help @Monokai, buy the PRO license, does this affect?

**Comment by Monokai** [comment]
.scss and .sass icons should both work. the scopes for this icon are: `source.sass, source.css.sass, source.scss, source.css.scss`. I suspect it's conflicting file definitions from different themes ([see this issue above](https://github.com/Monokai/monokai-pro-sublime-text/issues/6#issuecomment-308731333)).

**Comment by benfrain** [comment]
Just a FYI for 2021 – it was another theme for me. As soon as I removed Enki theme the icons appeared.
