### ISSUE TITLE
How to Apply?

### ISSUE THREAD

**Issue by abdulmanan7** [Monokai/monokai-pro#7]
No proper documentation available. 
i have successfully install the theme but now how to apply it .
i check all places no reference on how to use it.

**Comment by Monokai** [comment]
@abdulmanan7 `Quick panel ‣ Monokai Pro: select theme`

Maybe I should show a pop-up with this info upon installing this theme.

**Comment by abdulmanan7** [comment]
sorry brother on my machine Quick panel not working.
i found the solution my self thanks.

"theme": "Monokai Pro.sublime-theme"
